language: node_js
node_js:
  - 6
cache:
  directories:
    - ~/.npm
    - node_modules
install:
  - yarn
script:
  - http-server -p 1111 . > http.log 2>&1 &
  - $(npm bin)/cypress run
  - fuser -k 1111/tcp
